### ISSUE TITLE
DEV-4: Name of the room

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/SimpleChat-Socket.io#10]
I propose to specify somewhere (maybe implement the Header or something like this) the name of the current room. Also, would be great to make it easy-sharable - for example onclick event of the room name copies automatically the name to the clipboard, so to share this name the user only needs to paste and send it to his/her friends. I have seen the same principle for example for "Clone" button of GitHub, so we can use it as a reference:
![image](https://user-images.githubusercontent.com/26466644/37866595-17b1fcd4-2f8d-11e8-940a-2b11051c2c25.png)

Before implementing this issue, describe please in details your ides, so it would be approved before implementation.

To work on this issue, please use a branch **DEV-4** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.

**Comment by TetianaKlymchuk** [comment]
I want to take this one! Can I?

**Comment by KovDimaY** [comment]
Shure! Go ahead! 👍

**Comment by TetianaKlymchuk** [comment]
I have implemented all the requested functionality! Visually it looks like this:

![image](https://user-images.githubusercontent.com/28005338/46586169-ca151400-ca7a-11e8-89e5-2cba25ae1741.png)

For the long names:
![image](https://user-images.githubusercontent.com/28005338/46586188-0c3e5580-ca7b-11e8-8599-f69a1b5cb8a5.png)

Let me know what do you think, please! :D

**Comment by KovDimaY** [comment]
I think it is more than ok! You can create a PR! :D
Thank you! 👍

**Comment by KovDimaY** [comment]
@TetianaKlymchuk, the PR is approved an merged! Great job! 
I close the issue! 👍
