### ISSUE TITLE
DEV-17: Update README.md

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/SimpleChat-Socket.io#35]
For the next release it is planned to modify a lot the layouts and some functionalities of the application, so as the **README.md** file has screenshots and a description of the project, it has to be modified with the latest changes before the release (merge to master).

Also would be great to add some **badges** like these:
![GitHub](https://img.shields.io/github/license/mashape/apistatus.svg) 
![GitHub version](https://img.shields.io/badge/version-2.0.0-brightgreen.svg)

This issue should be opened until the release and should be closed just before the **merge to the master** branch.

To work on this issue, please use a branch **DEV-17** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.ct.

**Comment by TetianaKlymchuk** [comment]
I want to take this one! :D

**Comment by KovDimaY** [comment]
Sure, why not! 👍 
Go ahead!

**Comment by TetianaKlymchuk** [comment]
I have created a PR! @KovDimaY, could you take a look, please?

**Comment by KovDimaY** [comment]
Great job! I have merged the PR so the issue can be closed!
