### ISSUE TITLE
DEV-19: Add favicon to the project

### ISSUE THREAD

**Issue by KovDimaY** [KovDimaY/SimpleChat-Socket.io#38]
At the moment there is no favicon for the website and it does not look nice:
![image](https://user-images.githubusercontent.com/26466644/46581531-8d292d00-ca3a-11e8-9627-17815ff55934.png)

The icon should be added to the 3 main pages:
- [x] Join Page (Home)
- [x] Chat
- [x] 404 (Not Found)

As an idea what should be used as the icon:
![image](https://user-images.githubusercontent.com/26466644/46581556-eabd7980-ca3a-11e8-895e-4eb7d87fe01b.png)

To work on this issue, please use a branch **DEV-19** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.

**Comment by TetianaKlymchuk** [comment]
I am going to take this one! :)

**Comment by KovDimaY** [comment]
Perfect! Thank you!

**Comment by TetianaKlymchuk** [comment]
This is how it looks with the icon:
![image](https://user-images.githubusercontent.com/28005338/46581699-6caea200-ca3d-11e8-8808-c2b024357861.png)

Is it ok? Should I create a PR?

**Comment by KovDimaY** [comment]
Now I think that orange color does not fit to the palette of the project... 
Could you find something blue, please?

**Comment by TetianaKlymchuk** [comment]
What about this?

![image](https://user-images.githubusercontent.com/28005338/46581809-d3808b00-ca3e-11e8-8a0d-3769c5a0602e.png)

**Comment by KovDimaY** [comment]
Perfect! :)
Create a PR!

**Comment by KovDimaY** [comment]
The PR is merged, this issue can be closed!
